name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'bugfix'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '♻️ Refactoring'
    labels:
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⚙️ Configuration'
    labels:
      - 'config'
      - 'ci'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'tests'

change-template: '- $TITLE (@$AUTHOR) in $PULL_REQUEST'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'bugfix'
      - 'bug'
  default: patch

template: |
  ## Changes in this Release

  $CHANGES

  **Contributors:** $CONTRIBUTORS

autolabeler:
  - label: 'feature'
    title:
      - '/^feat/i'
  - label: 'bug'
    title:
      - '/^fix/i'
      - '/^bugfix/i'
  - label: 'documentation'
    title:
      - '/^docs/i'
      - '/^doc/i'
  - label: 'refactor'
    title:
      - '/^refactor/i'
  - label: 'config'
    title:
      - '/^chore/i'
      - '/^ci/i'
